[package]
name = "yew-app-example"
version = "0.1.0"
edition = "2018"

[dependencies]
yew = "0.19"
yew-router = "0.16"
gloo = "0.5"
shared-components = { path = "../components" }
core = { path = "../core" }